# Logo
logo_image_source: http://www.codeblocq.com/assets/projects/hexo-theme-anodyne/assets/anodyne.svg

# Index Page
index_banner_text: 極簡部落格
index_banner_text_secondary: 何謂極簡？懶。
index_font_awesome_icon_css: fa fa-thumbs-up

# Header
menu:
  首頁: /
  歸檔: /archives
  # 關於: /about
  # 聯繫: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: M/YY
archive_font_awesome_icon_css: fa-folder-open

tag_date_format: MMM YYYY
tag_font_awesome_icon_css: fa-hashtag

# About Widget
about_widget_avatar_url: /images/profile.jpg
about_widget_text: "喜歡將問題分解，各個擊破。<br>喜歡寫容易維護，可讀性佳的程式。<br>喜歡將事情自動化，減少做同樣的事情。"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: exia56-blog

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://www.facebook.com/
    fa_icon: fa-facebook
  - url: https://github.com/exia56
    fa_icon: fa-github
  - url: mailto:exia5693@gmail.com
    fa_icon: fa-envelope

# Footer about
footer_about: "All right reserved | Design & Hexo <a class=\"link dim white\" href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
